### PR TITLE
13: Creating table class from Postgres system files

### LINKED ISSUE #4: Reading table from PG does not fill int indexes and PK
## Describe the bug
The filling of `DBTable` from Postgres skips indexes and the PK (they are empty)

## Expected behavior
Add the missing queries to extract this information). Place marked with `TODO AbsaOSS/ultet#4` in the code.

### LINKED ISSUE #13: Creating table class from Postgres system files
## Background
Tables need to be represented within the application for further analysis and eventually change SQL entries

## Feature
The table class is to be filled from Postgres system tables.

**NB!**
Function to return `Option` of the table class, in case the table does not exist (then `None` is returned)

## Hint
This is for functions, but query or table won't be that different.
```sql
SELECT
    n.nspname,
	A.rolname,
	T.typname AS returntype,
    p.*
    
FROM 
    pg_catalog.pg_namespace n JOIN 
    pg_catalog.pg_proc p ON p.pronamespace = n.oid JOIN
	pg_catalog.pg_authid A ON  p.proowner  = A.oid JOIN
	pg_catalog.pg_type T ON p.prorettype = T.oid
WHERE 	
	n.nspname NOT IN ('public', 'pg_catalog', 'pg_toast', 'information_schema') AND
	p.prokind = 'f'
ORDER BY n.nspname, p.proname
```

Depends on AbsaOSS/fa-db#8`2

### PR DESCRIPTION
**Pull request by benedeki**
Adds the ability to read table definition, its fields and indexes from PG system tables. 
Some renames and classes placement changes. 

NB!
Not tested for full functionality. That will come after further changes.

Closes #13
Fixes #4

### CODE REVIEW

File: src/main/resources/queries/pg_table_columns.sql [hunk 1]
```diff
@@ -0,0 +1,26 @@
+SELECT
```
Comment (salamonpavel) [inline src/main/resources/queries/pg_table_columns.sql:1]: Files in the resource folder should be documented.

File: project/Dependencies.scala [hunk 2]
```diff
@@ -29,6 +29,7 @@ object Dependencies {
     "io.circe" %% "circe-core" % "0.14.2",
     "io.circe" %% "circe-generic" % "0.14.2",
     "io.circe" %% "circe-parser" % "0.14.2",
-    "io.circe" %% "circe-generic-extras" % "0.14.2"
+    "io.circe" %% "circe-generic-extras" % "0.14.2",
```
Comment (salamonpavel) [inline project/Dependencies.scala:32]: We could follow the same conventions as in other projects with respect to how we specify versions of dependencies and so on. Not necessarily as part of this PR, but tickets for this could be created as we go and references left in the code.

File: src/main/scala/za/co/absa/ultet/dbitems/extractors/DBTableFromPG.scala [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+    runQuery(ResourceReader.sql("pg_table_indexes"), schemaAndTableNameSetters){ queryResult =>
+      if (queryResult.isEmpty) {
+        None
+      } else {
+        val row = queryResult.next()
+        val dbTable = DBTable(
+          tableName = tableName,
+          schemaName = schemaName,
+          primaryDBName = databaseName,
+          owner = UserName(row.getString("table_owner").get),
```
Comment (salamonpavel) [inline src/main/scala/za/co/absa/ultet/dbitems/extractors/DBTableFromPG.scala:51]: Constants could be extracted into some object. Won't comment on other occurrences, but this applies to the whole application. Please create a ticket for it.

File: src/main/scala/za/co/absa/ultet/util/ResourceReader.scala [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+
+package za.co.absa.ultet.util
+
+import scala.io.Source
+
+object ResourceReader {
+  private val lineSeparator = "\n"
+
+  def sql(sqlName: String): String = {
+    val filename = s"queries/$sqlName.sql"
```
Comment (salamonpavel) [inline src/main/scala/za/co/absa/ultet/util/ResourceReader.scala:25]: Why is it required to place queries into queries folder? Shouldn't that be configurable?

File: src/main/scala/za/co/absa/ultet/util/ResourceReader.scala [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package za.co.absa.ultet.util
+
+import scala.io.Source
+
+object ResourceReader {
```
Comment (salamonpavel) [inline src/main/scala/za/co/absa/ultet/util/ResourceReader.scala:21]: This approach of reading a file is valid and correct, but I would suggest using scala.util.Using :-) as it handles the closing of given resource automatically. See the snippet below. Really simple and much more concise.
```scala
val fileContent: Try[String] = Using(Source.fromFile(filePath)) { source =>
  source.getLines().mkString("\n")
}
```

**Comment by salamonpavel** [comment]
The application already seems to be packed with a lot of functionality, which is fantastic! I've taken a look at the changes you've made and left a few comments. None of them are critical, but I believe they could enhance your code, so please consider them when you have a moment.

I wish I could provide more detailed feedback on the code itself. However, I'll need to familiarize myself with the overall application first. Unfortunately, the current state of the project lacks a README file for documentation, and there are no comments within the code. Additionally, the lack of tests makes it challenging to understand the expected behavior of the code. These factors make collaboration a bit difficult.

I strongly recommend adding a comprehensive README and comments in your code to provide context and make it easier for others (and future you) to understand. Also, consider adding tests to ensure your code behaves as expected and to prevent potential bugs from being introduced in the future. Keep up the good work!

File: src/main/scala/za/co/absa/ultet/dbitems/extractors/DBTableFromPG.scala (hunk 3 above)
Comment (salamonpavel) [reply src/main/scala/za/co/absa/ultet/dbitems/extractors/DBTableFromPG.scala:51]: The argument for using constants is maintainability. If you use the same string in multiple places and need to change it, you would have to find and change every occurrence. With a constant, you only need to change it in one place. The "table_owner" string might in fact be used only once at this point, but that's not the case for other hardcoded strings, file names, etc. Adopting the practice of using constants instead of hardcoded strings will spare you from potential problems and make your code more maintainable in the future.

File: project/Dependencies.scala (hunk 2 above)
Comment (benedeki) [reply project/Dependencies.scala:32]: Unfortunately I am not sure, we have yet a settled standard for this. In any case, I added constants for the versions at least (grouped in its own object).

File: src/main/scala/za/co/absa/ultet/dbitems/extractors/DBTableFromPG.scala (hunk 3 above)
Comment (benedeki) [reply src/main/scala/za/co/absa/ultet/dbitems/extractors/DBTableFromPG.scala:51]: Sure in cases, when the value is used multiple times. But here they are used exactly ones, and not expected to be used anywhere else in future.

Comment (benedeki) [reply src/main/scala/za/co/absa/ultet/dbitems/extractors/DBTableFromPG.scala:51]: Well, yeah. But they come from different queries. So it's a "false repeat". Would the column name change in one of the queries, it would cause a split.
I had tried to have constants for query column names in one my previous projects. Trust me, just adds overhead and no gain in return.
